# Generated by Django 4.1.3 on 2023-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_created_dare_variation_created_date_and_more'),
        ('carts', '0002_rename_data_add_cart_date_added_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
